version: '3.1'
services:
  API:
    image: 'school'
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/spring-jdbc-docker-school
      - SPRING_DATASOURCE_USERNAME=lenskyi
      - SPRING_DATASOURCE_PASSWORD=lenskyi

  PostgreSQL:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=lenskyi
      - POSTGRES_USER=lenskyi
      - POSTGRES_DB=spring-jdbc-docker-school
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=spring-jdbc-docker-school --username=lenskyi"]
      interval: 10s
      timeout: 5s
      retries: 5