version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_jdbc_lenskyi_app_cont
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://school_jdbc_lenskyi_db_cont:5432/school_db
    stdin_open: true
    tty: true
    volumes:
      - logs:/logs

  db:
    image: postgres:15-alpine
    container_name: school_jdbc_lenskyi_db_cont
    environment:
      POSTGRES_USER: lenskyi
      POSTGRES_PASSWORD: lenskyi
      POSTGRES_DB: school_db
    ports:
      - '5432:5432'
volumes:
  logs: