DROP TABLE IF EXISTS school.course CASCADE;
DROP TABLE IF EXISTS school.group CASCADE;
DROP TABLE IF EXISTS school.student CASCADE;
DROP TABLE IF EXISTS school.student_course CASCADE;
DROP SCHEMA IF EXISTS school;